### ISSUE TITLE
allow disabling of repeat expand region commands

### ISSUE THREAD

**Issue by mikedmcfarland** [magnars/expand-region.el#157]
It'd be nice to be able to disable expand regions repeat command functionality.

When you `(expand-region)`, `er/prepare-for-more-expansion` looks at the last pressed key, so that it can allow you to expand the region again by repeating it.

That's pretty sweet!
Except in my case it interferes. For example
```
(global-set-key (kbd "C-S-SPC") 'er/contract-region)
(global-set-key (kbd "C-SPC") 'er/expand-region)

(define-key evil-visual-state-map (kbd "SPC c") 'some-action)
``` 
I'd like to use space to trigger another action, but expand-region has made a temporary overlay map, and space now immediately expands the region again. 

I'd like to just turn this feature off, and be able to use C-SPC/C-S-SPC instead.

I apologize if there is a easy, or documented way around this. I didn't see one.

**Comment by magnars** [comment]
Hi Mike, here's from my config:

```
;; Don't use expand-region fast keys
(setq expand-region-fast-keys-enabled nil)
```

**Comment by mikedmcfarland** [comment]
Thanks, exactly what I was looking for!
