### ISSUE TITLE
Expand region change the behavior after close parenthesis.

### ISSUE THREAD

**Issue by uk-ar** [magnars/expand-region.el#163]
er/expand-region change the behavior after close parenthesis.
1. On open parenthesis and has white space after close parenthesis.
![_scratch__9](https://cloud.githubusercontent.com/assets/235329/6988446/7c6b19ac-da8c-11e4-9d90-a0714fec9c4b.png)
![_scratch__8](https://cloud.githubusercontent.com/assets/235329/6988452/8f80d43c-da8c-11e4-80c9-4fb805392b3a.png)
2. On open parenthesis and has no white space after close parenthesis.
![_scratch__7](https://cloud.githubusercontent.com/assets/235329/6988451/8f7a44a0-da8c-11e4-9c4b-97e15646ffde.png)
![_scratch__6](https://cloud.githubusercontent.com/assets/235329/6988450/8f768626-da8c-11e4-9213-147345a1a02e.png)
There is not test about it in mark-pairs.feature.
Is this expected behavior or bug?

**Comment by magnars** [comment]
I'd call that a bug.
