### ISSUE TITLE
Symbol's function definition is void: save-mark-and-excursion

### ISSUE THREAD

**Issue by geraldus** [magnars/expand-region.el#165]
Since some time `expand-region` stop working correctly for me failing with following error message after each invocation: 

```
er--expand-region-1: Symbol's function definition is void: save-mark-and-excursion
```

I guess this some kind of misconfiguration in my init script.

**Comment by magnars** [comment]
What version of Emacs are you running?

**Comment by geraldus** [comment]
Oh, sorry, I've forgot to mention it. I have Emacs universal binary of version `24.5.1`.

**Comment by magnars** [comment]
How do you install it?

**Comment by geraldus** [comment]
I install it from `MELPA`.

**Comment by magnars** [comment]
Thanks. I'll investigate.

**Comment by magnars** [comment]
I have now installed Emacs `24.4`, `24.5` and `25`, and installed expand-region from MELPA on all these versions. No such error. I suspect there are some old compiled files hanging around or some such shenanigans.

Can you reproduce it on a clean Emacs?

**Comment by geraldus** [comment]
@magnars Thank you for your hint! I've moved `~/.emacs.d/elpa` folder and reinstalled all packages again. Now the issue is not relevant.
