### ISSUE TITLE
Expand region don't include the < and > tags.

### ISSUE THREAD

**Issue by ReneFroger** [magnars/expand-region.el#167]
### Setup:
GNU Emacs GUI version 24.4.51.1 (x86_64-w64-mingw32) 
[Compiled from Harroogan Emacs.](https://bitbucket.org/Haroogan/emacs-for-windows/)
Company Mode, using the latest version of Company from GitHub
Windows 7 x64 bit.

### Situation:
For example, [] = the cursor, and In `web-mode`:

`<div> foo bar [] foo bar </div>`

And then I call expand-region, he will not select everything between the `<div>` tags. I call it again, but then the `<div>` tags got included.
    
 Seems a bug to me?

**Comment by magnars** [comment]
The expand-region support for `web-mode` is limited to using web-mode's own `web-mode-mark-and-expand`. Does that work as intended?

**Comment by ReneFroger** [comment]
Thanks for your answer. `web-mode-mark-and-expand` is working fine in this case. then everything between the `>` and `<` tags will be selected. 

So I'm wondering why expand-region is not working together with `web-mode-mark-and-expand`. 

But I call expand-region with a key, then the function `er/expand-region` will be called. And it's not working together with the `web-mode-mark-and-expand`. Any suggestion in order to track this down?

**Comment by magnars** [comment]
I'm not sure when or how the two have diverged, but I would recommend just binding your expand-region key to `web-mode-mark-and-expand` in web-mode.

**Comment by ReneFroger** [comment]
I never could guess there was a thight integration between expand-region and web-mode. 

For reference, qqI solved it with 
```
(evil-define-key 'visual web-mode-map
  (kbd "v") 'web-mode-mark-and-expand
  )
```

So pressing `vv` will expand the region, by standards of `web-mode`, and press `v` again to expand it.
