### ISSUE TITLE
After copy with CUA, cursor keys still adjust region

### ISSUE THREAD

**Issue by rneatherway** [magnars/expand-region.el#169]
When selecting a region with shift-cursor and then copying with `C-c` thanks to CUA, I am used to the next movement command unselecting the region. If I choose a region with expand-region, though, this doesn't happen. Is this possible?

**Comment by magnars** [comment]
Sounds like cua-mode is doing some cunning tricks here. I know very little about CUA, unfortunately. Normally expand-region does not care about what happens after a region is selected. If you can locate a cua-expert, maybe there is a flag that needs to be set or something along those lines?

**Comment by rneatherway** [comment]
OK, sounds like this isn't the fault of expand-region.
