### ISSUE TITLE
Could ` be considered as a delimiter? 

### ISSUE THREAD

**Issue by ReneFroger** [magnars/expand-region.el#174]
Thanks for sharing this package! 

When I'm working in `markdown-mode`, I noticed that expand-region doesn't consider the \` as a delimiter, like `[`, `(`, `'` or `"`.

Could the \` be added to the expand-region list of delimiters?

**Comment by wilkystyle** [comment]
You can add the backtick character to the syntax table for `markdown-mode`. I have the following in my `.emacs`:

```lisp
(add-hook 'markdown-mode-hook (lambda () (modify-syntax-entry ?\` "\"`")))
```

**Comment by ReneFroger** [comment]
Very clever... I didn't knew such function as `modify-syntax-entry` exists... thanks for your help, @wilkystyle it's appreciated!
