### ISSUE TITLE
end of region - simple feature request

### ISSUE THREAD

**Issue by Pitometsu** [magnars/expand-region.el#180]
Is it will be hard for you to add next feature as an option: if point already after thing that will be marked, put it here after region selection, not on the begin?

**Comment by magnars** [comment]
That sounds doable. Maybe you want to give it a shot yourself?

PS! I read your issue as "End of religion - simple feature request". That would be slightly harder to pull off. :-)

**Comment by magnars** [comment]
Ack, I just realized that Expand Region is headed for Emacs core, so you should only work on this feature if you have your FSF papers signed. Otherwise I can't accept it.

**Comment by Pitometsu** [comment]
I didn't understand: may I make it as a PR, or you can, or nobody can, but @rms

**Comment by Pitometsu** [comment]
> End of religion

nice try **: )**

**Comment by magnars** [comment]
Anyone who has signed copyright assignment papers from FSF can contribute.

**Comment by Pitometsu** [comment]
I don't :'(
Do you?
Or it's not an a hard issue to sign?

**Comment by magnars** [comment]
No, it's not hard. E-mail FSF at assign@gnu.org and say you want to sign copyright assignment for Emacs.

**Comment by Pitometsu** [comment]
Thanks for suggestion! So I'll be glad to contribute this micro-patch, but should wait, until papers delivered by post to FSF.

**Comment by magnars** [comment]
:+1:

**Comment by Pitometsu** [comment]
Ok, I have some time to implement it now. [Here](https://drive.google.com/file/d/0B0iHSg_RdihOUmY1NWtJMUx1WFJFMDZIbTdsa19sd29iXzFz/view?usp=sharing) signed FSF copyright.

**Comment by AndreaOrru** [comment]
This should probably be closed now. ;)
