### ISSUE TITLE
strange behaviour in latex-mode

### ISSUE THREAD

**Issue by dinojr** [magnars/expand-region.el#182]
Recently, expand-region started acting up in latex-mode. Consider the following in a latex-mode buffer, and point at ^

[ two ^strings ] 

Subsequent invocations of er/expand-region marks (I'm using _ to delimit the marked region)
[ two ^_strings_ ]
[ two ^_strings ]_
[ two ^_strings ]                                                                                                                                       _
(yes, to the end of the line)
_[ two ^strings ]                                                                                                                                       _

I never get mark around the brackets as expected.

**Comment by magnars** [comment]
The latex support in expand-region hasn't changed in a long while. Did you upgrade your Emacs before this happened? That could mean our latex support is now outdated. If not, maybe some other package is interfering?

**Comment by dinojr** [comment]
Your suggestion prompted me to check my init file. It turns out that expand-region was somehow loaded twice: once by package and another older version through require later on. It seems remove the latter fixes the problem. I'll see if it resurfaces.
