### ISSUE TITLE
Preferred method to extend ``er/try-expand-list``

### ISSUE THREAD

**Issue by wavexx** [magnars/expand-region.el#183]
What's the preferred method to append mode-specific entries to ``er/try-expand-list``?

I defined some custom mark functions, and indeed all of them are mode specific. So I ended up using ``er/enable-mode-expansions``, but in each function I need to make ``er/try-expand-list`` buffer-local.

Is there a reason ``er/try-expand-list`` cannot be buffer-local by default? So that we could simply use setq-default/add-to-list normally?

**Comment by magnars** [comment]
Setting it buffer-local by default precludes adding more global expansions. You're free to set it buffer local in your settings, of course.

**Comment by wavexx** [comment]
But is there a reason why ``er/enable-mode-expansions`` couldn't do that by default when the hook list for the current mode is non-empty?

I don't see a case where a mode handler would be called to set global expansions.

**Comment by magnars** [comment]
I don't see any big issues with setting it to buffer-local in `er/enable-mode-expansions`. However, It's a side-effect that doesn't belong there. If you were to manually invoke the function to add mode expansions, it would no longer guard itself against polluting the global try-list. 

I don't see the big issue with doing `(set (make-local-variable 'er/try-expand-list) ...)`.

**Comment by wavexx** [comment]
On 16/11/15 19:09, Magnar Sveen wrote:
> I don't see any big issues with setting it to buffer-local in
> |er/enable-mode-expansions|. However, It's a side-effect that doesn't
> belong there. If you were to manually invoke the function to add mode
> expansions, it would no longer guard itself against polluting the global
> try-list.
> 
> I don't see the big issue with doing |(set (make-local-variable
> 'er/try-expand-list) ...)|.

Fair enough. I was just reading through the various mode expansions, and
it just felt incredibly repetitive.
