### ISSUE TITLE
Region set by expand-region doesn't get unset by motion commands

### ISSUE THREAD

**Issue by npic** [magnars/expand-region.el#185]
I'm not sure whether it's a bug or a feature. When I set the region with er/expand-region, I sometimes think like "nah, let's edit this piece a bit later", and want to move elsewhere. But the motion commands won't reset the region then - they will drag the one end of the region constantly. I would expect the motion commands to reset the region and just move the point.
Hint: you probably want to take a look at mouse.el. The mouse-set-region-1 function has a snippet of code that should solve the issue (but that's just a guess).

**Comment by magnars** [comment]
There are two kinds of regions in Emacs. The modern one that is selected by shift-moving and deselected by moving - and the old one that is anchored by the mark. Expand region uses the latter.

**Comment by npic** [comment]
So, there's a reason behind this decision, and the actual behaviour is a feature rather than a bug, right?

**Comment by magnars** [comment]
Yes. I don't use shift-selection.
