### ISSUE TITLE
Incorrect expansions

### ISSUE THREAD

**Issue by plantarum** [magnars/expand-region.el#186]
To reproduce, open `emacs -Q` and eval the following code:

```{lisp}
(require 'package)
(setq package-load-list
      '((expand-region t)))
(package-initialize)

(require 'expand-region)
(setq er--show-expansion-message t)
(global-set-key (kbd "C-=") 'er/expand-region)
```

Split the frame and open the `*Messages*` buffer in one window.

Move point to the first 'n' of (expand-region t).

Press `C-=`. Instead of marking the word `expand` as expected, `nd-region` is highlighted. The *Messages* buffer reports that `er/mark-word` and `er/mark-inside-quotes` have been called. This is odd, as calling either of those commands directly will not produce the same region. Called on their own, they mark the region you expect (the entire word `expand`, or nothing, respectively).

![2016-01-19-171430_271x100_scrot](https://cloud.githubusercontent.com/assets/5727138/12433943/d6b47938-bed1-11e5-8ee1-39c9fef6c0ee.png)

Press `=`. The region expands to `nd-region t)` and the *Messages* show `er/mark-symbol` and `er/mark-comment` have been called.

![2016-01-19-171445_277x99_scrot](https://cloud.githubusercontent.com/assets/5727138/12433964/ea108b52-bed1-11e5-9a02-37f033c4c785.png)

Press `=` again. The region expands to `(expand-region t)` and the *Messages* buffer shows `er/mark-outside-pairs`. This is the first time the reported command matches the selected region.

![2016-01-19-172645_261x90_scrot](https://cloud.githubusercontent.com/assets/5727138/12433991/09d9492e-bed2-11e5-812a-c9545cbb664e.png)

Any ideas what's happening here?

GNU Emacs 25.0.50.2 (x86_64-pc-linux-gnu, GTK+ Version 3.18.5) of 2015-12-24
Expand region  version 20150902.558 from MELPA

Here's the value of `er/try-expand-list`, which should be the default value given the config above:

```{lisp}
(er/mark-word er/mark-symbol er/mark-symbol-with-prefix er/mark-next-accessor 
 er/mark-method-call er/mark-inside-quotes er/mark-outside-quotes er/mark-inside-pairs 
 er/mark-outside-pairs er/mark-comment er/mark-url er/mark-email er/mark-defun)
```

**Comment by magnars** [comment]
Thanks for the report. I stopped running the tests on unstable releases of Emacs, since it would break all the time - and then work properly once released. I'll keep an eye on this once 25 is released.

**Comment by plantarum** [comment]
Ok. I just reverted to Emacs 24.5.50.1 and everything is fine there. Thanks!
