### ISSUE TITLE
`er/expand-region` marks too much

### ISSUE THREAD

**Issue by joostkremers** [magnars/expand-region.el#195]
This has been happening a while now, can't remember exactly when it started. If I have the following Lisp code:

![screenshot from 2016-06-03 11 44 12](https://cloud.githubusercontent.com/assets/191630/15775240/19da8698-2981-11e6-9d88-dd8f8142d54a.png)

with point before `(while...` as indicated, `M-x er/expand-region` marks not just the sexp `(while...`, but also the text up to the closing paren of the containing sexp:

![screenshot from 2016-06-03 11 43 03](https://cloud.githubusercontent.com/assets/191630/15775284/5f37e9c4-2981-11e6-9eb1-63465b610907.png)

What I expect to be selected (which used to be the case up until maybe two months ago), is of course just the sexp `(while...`:

![screenshot from 2016-06-03 11 43 15](https://cloud.githubusercontent.com/assets/191630/15775280/51757d92-2981-11e6-8aa7-a202dd2880fe.png)

I tried this with `emacs -Q` as well, but it still happens. The screen shots were made with Emacs 25.0.92.1, but I just compiled and installed 25.0.94.1 and the problem still occurs.

Like I said, this has been happening for a while, though I'm not sure how long exactly. I didn't report it earlier because I figured it would be fixed quickly, but unfortunately it hasn't.

Any idea what's going wrong here?

**Comment by hedning** [comment]
I can reproduce this on 25.0.95 (with spacemacs), but not on 24.5. In addition expansion on symbols only selects the right side of the symbol:
![expand](https://cloud.githubusercontent.com/assets/71978/16064924/fd3781f2-32a5-11e6-84eb-5fd2b49775c1.gif)

**Comment by joostkremers** [comment]
Thanks for confirming. Good to know it only happens on Emacs 25. I did switch from 24 to 25 a month or two ago, but I hadn't noticed the problem correlated with that switch.

**Comment by joostkremers** [comment]
Well, I figured out the cause of the problem. Turns out the byte code was still compiled by Emacs 24, which apparently didn't work properly under Emacs 25. Recompiling the package (actually uninstalling and reinstalling) fixed things.

**Comment by hedning** [comment]
Ah, that's good to know. Guess this can be closed then.

**Comment by vadali** [comment]
Hey, I am experiencing the same thing on emacs 25. However the elc are not compiled by emacs 24.. 

I tried reinstalling the package, however I still get the mentioned behavior: 
If point is in the middle of a symbol, it will select the rest of the symbol from point forward, then until the end of the s-exp, then the entire s-exp..

Any clues?

**Comment by joostkremers** [comment]
Well, if recompiling (reinstalling) doesn't help, it seems you have another issue. I'm not familiar enough with `expand-region` to be able to help, so my best suggestion is to start a new issue. Your problem should get more attention that way.
