### ISSUE TITLE
er/expand-region just marked a half word, not whole word in macOS

### ISSUE THREAD

**Issue by futurist** [magnars/expand-region.el#196]
`er/expand-region` work perfect in other system, but not in my macOS, see snapshot:

![2016-07-04 6 39 10](https://cloud.githubusercontent.com/assets/159167/16547999/5963d776-41b2-11e6-810b-a9e305803f81.png)

This is the first time run `er/expand-region`, it's only looking forward. After run: 

`(setq er--show-expansion-message t)`

The message logged:

```
er/mark-word
er/mark-inside-quotes
```

Is it the right behavior?

macOS: 10.9
Emacs: 25.0.94

**Comment by magnars** [comment]
That's certainly not the right behavior. I don't think it's macOS that is the problem, tho, but your Emacs version. I don't support unstable releases, since it's been quite the pain over the years trying to do so. 24.5 is the latest stable release.

**Comment by futurist** [comment]
Same version 25.0.94 works fine in windows 10 64bit. Maybe it's a macOS build version issue?

**Comment by futurist** [comment]
I'm confirmed this problem is due to **elc** files of cached old version of `expand-region.el` from elpa, remove all the **elc** files, it's working now!

Also worked in version 25.1.1, both Mac and Windows.
