### ISSUE TITLE
expand-region no longer working as expected

### ISSUE THREAD

**Issue by jethrokuan** [magnars/expand-region.el#200]
For some reason, expand-region's behaviour has changed across all modes for me, and I can't determine why.

![er](https://cloud.githubusercontent.com/assets/1667473/18039313/4c2a118a-6dd4-11e6-9628-4008fa97872c.gif)

In clojure-mode, `er/mark-clj-word` works as expected, for example, so i'm baffled.

**Comment by magnars** [comment]
Did you upgrade your Emacs to some 25.x version maybe? I stopped supporting non-stable Emacsen some years ago when they kept breaking things.

**Comment by jethrokuan** [comment]
@magnars you're absolutely right, downgrading to Emacs24 worked for me.

**Comment by nloyola** [comment]
Right before upgrading to Emacs 25.1.1, I removed all packages in `$HOME/.emacs.d/elpa`. I re-installed all my packages and `expand-region` works as intended.

**Comment by magnars** [comment]
Aha, that's interesting information, @nloyola. I guess the `.elc` files compiled by E24 doesn't work properly in E25. Thanks!

**Comment by arnemart** [comment]
Confirmed, deleting all `.elc` files and recompiling fixed this issue for me.
