### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by gavv** [magnars/expand-region.el#202]
Hi!

Thanks for this great module.

I'd like to package it for Gentoo. Could you tag a new release? The latest one was in 2014.

**Comment by DamienCassou** [comment]
Same problem here on nixpkgs.

**Comment by DamienCassou** [comment]
A git tag would be enough as it would update the melpa-stable package.

**Comment by magnars** [comment]
I will release a new version once we have figured out what's going wrong in the latest Emacs release. Thanks for the nudge. And thanks for doing the packaging work.

**Comment by Trevoke** [comment]
@magnars if you are referring to #201, as far as I'm concerned, the only problem is that the code on MELPA stable (0.10.0) is two years old. I switched to MELPA and expand-region works like a charm.

**Comment by magnars** [comment]
I have finally tagged a new release, `0.11.0` for melpa-table.

**Comment by Trevoke** [comment]
Wonderful, thank you! :)
