### ISSUE TITLE
Expands to the right of a word on Emacs 25+

### ISSUE THREAD

**Issue by Grimscythe1983** [magnars/expand-region.el#203]
expand-region works as expected on Emacs ~24. If the cursor gets placed in the middle of a word expand-region selects the whole word (expanding to the left and to the right). However in Emacs ~25 it expands to the right only. It expands to the left as well, but only in the case of "bigger" areas, such as brackets or quotations, but not on a single word. Unexpected behaviour.

**Comment by nloyola** [comment]
This is probably a duplicate of #200.

**Comment by Grimscythe1983** [comment]
That is correct. I didn't notice that.
