### ISSUE TITLE
copy on expand?

### ISSUE THREAD

**Issue by jots** [magnars/expand-region.el#205]
Is it possible to have expand-region automatically copy the selection every time it creates a selection?  and also have a keystroke to unselect?  would like to expand-region mainly for side effect of copying.

**Comment by magnars** [comment]
Your copy command doesn't unselect? I expand-region then M-w to copy, which also unselects for me.

**Comment by krishnoid** [comment]
Can I bind a fast key for copy/kill?  I keep hitting w after an expand/shrink and tried looking up how to make that a standard binding, but got stuck.

Alternatively, is there a way to make the fast keys into a simple(r) keymap so people can bind their own single-keystroke functions after selecting a region?  I can submit that as a separate issue if you think it would be something worth implementing.

**Comment by mallt** [comment]
You could create your own custom keymap, f.ex.
```elisp
(setq your-custom-map (let ((map (make-sparse-keymap)))
                        (define-key map (kbd "w") 'kill-ring-save)
                        map))
```
and then set this keymap as the parent of the expand region keymap by adding this line [in expand-region-core.el below line 197](https://github.com/magnars/expand-region.el/blob/master/expand-region-core.el#L197):
```elisp
(set-keymap-parent map your-custom-map)
``` 

@magnars, do you think this would be a good candidate for a new customization option?

**Comment by krishnoid** [comment]
This works perfectly!  I actually have a real use for it immediately.  Thank you so much; if this was on emacs stackoverflow I'd award you a bounty for it.  Since this issue is closed, I can open a new issue if you think it's a good idea to recommend it.
