### ISSUE TITLE
er/expand-region breaks on Emacs 25

### ISSUE THREAD

**Issue by tmtxt** [magnars/expand-region.el#206]
After upgrading to Emacs 25, expand region does not expand as expected like on Emacs 24

The cursor is in the middle of **destructuring**, calling `er/expand-region` should expand to the whole word first, but it always expand to end of word.

![er](https://cloud.githubusercontent.com/assets/2741919/19213139/6b722568-8d8d-11e6-9122-cae750ef7428.gif)

expand-region version: 20160729.131
emacs version: GNU Emacs 25.1.1 (x86_64-apple-darwin13.4.0, NS appkit-1265.21 Version 10.9.5 (Build 13F1911)) of 2016-09-18 downloaded from https://emacsformacosx.com/

**Comment by magnars** [comment]
You need to remove the `.elc` files compiled for expand-region, then restart Emacs.

**Comment by tmtxt** [comment]
Thanks! It works now.
