### ISSUE TITLE
expand-region marking is confused by scroll and follow-mode

### ISSUE THREAD

**Issue by notuntoward** [magnars/expand-region.el#214]
My favorite use of expand-region is to watch its region marking to see where a nearly endless semantic region actually ends.  This is a visually difficult problem in lisp (all those parentheses) and especially so in certain verbose parts of Emacs lisp.

The problem is that the code between those parentheses is often longer than one screen; when I expand-region, the region marking goes off the bottom of the screen, and when I scroll down (scrollbar) to see it, the marking gets messed up.

I tried to avoid scrolling by using follow-mode to spread the code across multiple windows.  But unfortunately, expand-region marks only the first window.

**Comment by magnars** [comment]
Hi! I use it like that too. Try `C-x C-x` to jump to the end of the selection. :)

**Comment by notuntoward** [comment]
Thanks very much -- I didn't know about C-x C-x, and it's an at least 80% solution.

95% would be if the expand-region region markings worked across side-by-side follow-mode windows; then you could often see the entire function, all marked up.

100% would be if the region markers survived scrolling.

But 80% is already a big improvement, so thanks again!

**Comment by magnars** [comment]
expand-region only sets up a normal emacs region, so those cool extra features can be added, but outside of this package. :)
