### ISSUE TITLE
How select whole text inside quotes?

### ISSUE THREAD

**Issue by alexei28** [magnars/expand-region.el#217]
Windows 7
Emacs 24.5

I install package "expand-region"

Example#1:
"111111"

er/expand-region   - select text inside quotes. OK.

Example#2
"1111111-22222222222-3333333333"

er/expand-region   - select ONLY **1111111**  inside quotes.
But I need to select whole text inside quotes.

**Comment by magnars** [comment]
Try expanding the region two times then.

**Comment by lmdic** [comment]
Of course I can expand region many time (in my example 3 times). But I want do expand only once. Suppose I want select any GUID in quotes:
"**65af2382-d3ff-4f90-bc41-05ca56482526**" -
 I want run command **er/expand-region** only once.Is this a possible?

**Comment by magnars** [comment]
You can remove the offending expansion options from `er/try-expand-list`.
