### ISSUE TITLE
setting a mark with C-SPC after quitting expand-region with C-g

### ISSUE THREAD

**Issue by mallt** [magnars/expand-region.el#220]
After quitting from expand-region with `C-g`, setting a mark with `C-SPC` doesn't seem to work. After hitting `C-SPC` again however, the mark behavior seems to become normal again.

Any idea what could be causing this? Thanks!

(tested on emacs 25.1.4 in the `*scratch*` buffer)

**Comment by tdavis** [comment]
I noticed this as well, but hitting `C-SPC` doesn't restore the behavior. Sometimes I may have to mark/activate dozens of times before I can actually start marking again. It's super infuriating so I'm sure I would have noticed if it were present long-term.

**Comment by tdavis** [comment]
Two other things to note:

* Using `C-g`  isn't the only way for it to happen, at least for me. Just using a movement in a way that breaks the region is enough
* Anecdotally, I need to spam `C-SPC` for as many characters as there were in the selection at the time it was lost

**Comment by mallt** [comment]
Disabling shift-select-mode fixes this problem for me: `(setq shift-select-mode nil)`.

It seems commit acef6cc130dfc8f9b06677330cb87e4119ceb88b is linked with this behavior, but it seems to have the desired effect since the linked issue #190 is closed.

Since I'm not using shift-select-mode (it seems to be set to true by default), I'm fine with just disabling it.

@tdavis @ludwigpacifici Is it ok to close the issue?

**Comment by tdavis** [comment]
Oh thank gord! :pray:

**Comment by ludwigpacifici** [comment]
@mallt, it seems to work when `(setq shift-select-mode nil)`. However, it is a workaround. Is there a reason to disable `shift-select-mode` in order to use `expand-region`?

**Comment by mallt** [comment]
@ludwigpacifici I'm not sure about this, I don't fully understand the requested behavior of #190. But the fix is accepted so I guess this is the desired behavior?

@CyberShadow Could you maybe confirm this? Thanks!

**Comment by magnars** [comment]
If #190 broke shift-select-mode in some way, that was certainly not intended. I've never used shift-select-mode, so I'm merging stuff in sort of blind, which is unfortunate. I'm happy to accept any PR that fixes this, but won't be investigating on my own.

**Comment by CyberShadow** [comment]
> @CyberShadow Could you maybe confirm this? Thanks!

Fixing #190 certainly did not intend to introduce the behaviour described in this issue.

However, I use `shift-select-mode` exclusively for setting the region, so I can't offer any input on this, sorry!

**Comment by mallt** [comment]
It seems the problem is that the [`er--prepare-expanding`](https://github.com/magnars/expand-region.el/blob/master/expand-region-core.el#L47) function keeps on adding 'only to the `transient-mark-mode` variable on every expansion when `shift-select-mode` is active. When I check it's value it can contain several 'onlys (f.ex. `(only only only only only only only only only only only only . t)`).

A possible solution could be to only change the `transient-mark-mode` variable in the `er--prepare-expanding` function during a `er--first-invocation`. That would prevent adding 'only on every next expansion.

@magnars Do you think it would be safe to add this check, or do you see possible side effects of such a change? Thanks!

**Comment by magnars** [comment]
Good match, @mallt. That looks like a proper bug to me, and hopefully not something we're relying on. Have you tried your fix?

**Comment by mallt** [comment]
Thanks @magnars, I will test the change locally during the next couple of days. If all seems ok I'll submit a PR.

**Comment by magnars** [comment]
@mallt Excellent. 👍

**Comment by danrharms** [comment]
Is there any chance of merging this soon?

**Comment by magnars** [comment]
PR #225 is now merged.

**Comment by magnars** [comment]
This change has now been reverted as part of the rollback of #190. Let me know if that was in error.

**Comment by CyberShadow** [comment]
> Let me know if that was in error.

I'm not sure what the expected response is to that. IIUC, reverting this fix is going to break expand-region with shift-select-mode (which, I might mention again, is enabled *by default* in current Emacs versions). So, there is still a problem in expand-region, and #190 should probably be reopened.
