### ISSUE TITLE
Web-mode not working

### ISSUE THREAD

**Issue by kandiu** [magnars/expand-region.el#227]
I have this lines in my .emacs

```lisp

(use-package web-mode :ensure t
  :mode (("\\.html\\'" . web-mode)
         ("\\.css\\'" . web-mode)
	 ("\\.njk\\'" . web-mode)))

(use-package expand-region :ensure t
  :bind (("C-@" . er/expand-region))
  :config
  (add-hook 'web-mode-hook 'er/add-web-mode-expansions))
```

But it doesn't work well in web-mode. It just select the word and then the entire buffer. But if I change my web-mode buffer to html-mode and then again to web-mode, it works well!
Any help?

**Comment by mallt** [comment]
The web mode expansions should be added automatically, there should be no need to configure the `web-mode-hook` yourself. Do you notice any difference when you remove the `add-hook` from your use-package :config?

**Comment by kandiu** [comment]
Hello, thanks for your reply. Yes, I tried to remove the hook, it doesn't work either. But I discovered where is the problem. The :bind of use-package doesn't work. In fact, the following lines just works.

```lisp
(use-package expand-region :ensure t
  ;; :bind (("C-@" . er/expand-region)))
  :config
  (global-set-key (kbd "C-@") 'er/expand-region)
  (global-set-key (kbd "M-@") 'er/contract-region))
```
