### ISSUE TITLE
Allow for disabling of subword mode expansions

### ISSUE THREAD

**Issue by nloyola** [magnars/expand-region.el#254]
I have tried using expand-region with subword mode enabled and I really can't get used to it (i.e. commit c3de75c8460ab6d9380f1985404791ac4920fe88). I would like to go back to the way it worked previously. Could you provide a way of disabling subword expansion based on a configuration setting please?

**Comment by nloyola** [comment]
I'll submit a pull request shortly.

**Comment by magnars** [comment]
Fixed in https://github.com/magnars/expand-region.el/commit/5d9660985aff1aff92c1028b6f8bef57d30b3e28

**Comment by nloyola** [comment]
Thank you
